import 'grapesjs/dist/css/grapes.min.css';
import grapesjs from 'grapesjs';
// import plugin from 'grapesjs-preset-webpage';
import gjsForms from 'grapesjs-plugin-forms';
import newsletter from 'grapesjs-preset-newsletter';
import block_basic from 'grapesjs-blocks-basic';
import customCodePlugin from 'grapesjs-custom-code';
import pluginCountdown from 'grapesjs-component-countdown';
import navbarGrapes from 'grapesjs-navbar';
// import styleGradient from 'grapesjs-style-gradient';
import imageTui from 'grapesjs-tui-image-editor';
// import grapesjsTouch from 'grapesjs-touch';
// import styleBg from 'grapesjs-style-bg';
// import 'grapesjs/dist/css/grapes.min.css';
// import 'grapick/dist/grapick.min.css';
// import '../../node_modules/grapesjs/dist/css/grapes.min.css';
// import '../../node_modules/grapick/dist/grapick.min.css';
import grapesjsIcons from 'grapesjs-icons';

window.grapesjs = grapesjs;
// window.plugin = plugin;
window.gjsForms = gjsForms;
window.newsletter = newsletter;
window.block_basic = block_basic;
window.customCodePlugin = customCodePlugin;
window.pluginCountdown = pluginCountdown;
window.navbarGrapes = navbarGrapes;
// window.styleGradient = styleGradient;
window.imageTui = imageTui;
// window.grapesjsTouch = grapesjsTouch;
// window.styleBg = styleBg;
window.grapesjsIcons = grapesjsIcons;